import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tesla - Animation Site",
  description: "Generated by Khaled Ghonim",
  icons: {
    icon: "/Tesla LOGO.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-[Tesla]`}>{children}</body>
    </html>
  );
}
